apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjsapp
spec:
  selector:
    matchLabels:
      app: nestjsapp
  template:
    metadata:
      labels:
        app: nestjsapp
    spec:
      containers:
      - name: nestjsapp
        image: nestjsapp:latest
        ports:
        - containerPort: 3000
