apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: nestjsapp

images:
- name: nestjsapp
  newName: talessatiro/argocd-nestjs-app
  newTag: d385f8430af46d5e2b388c51c60ab0135f5aea4b
