apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: nestjsapp

images:
- name: nestjsapp
  newName: talessatiro/argocd-nestjs-app
  newTag: 2e9563c392a3c6a39ec36e47c3d2bb8f347bd045
