apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: nestjsapp

images:
  - name: nestjsapp
    newName: nestjsapp
    newTag: latest