name: CD
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image and push to dockerhub
        uses: docker/build-push-action@v1.1.0
        with:
          username: talessatiro
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: .
          file: ./application
          repository: talessatiro/argocd-nestjs-app
          tags: ${{ github.sha }}, latest