name: CD
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image and push to dockerhub
        uses: docker/build-push-action@v1.1.0
        with:
          username: talessatiro
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          path: ./application
          repository: talessatiro/argocd-nestjs-app
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: update k8s
        run: |
          cd k8s
          kustomize edit set image nestjsapp=talessatiro/argocd-nestjs-app:${{github.sha}}
          cat kustomization.yaml

      - name: commit
        run: |
          git config user.email "action@github.com"
          git config user.name "Deploy Action"
          git commit -am "change image tag"

      - name: push
        uses: ad-m/github-push-action@master
